### ISSUE TITLE
A table layout?

### ISSUE THREAD

**Issue by max-sixty** [EnricoMi/publish-unit-test-result-action#146]
We just got this working on xarray: https://github.com/pydata/xarray/pull/5537. It looks really promising, thanks for creating it!

Currently the text doesn't align that well — what do you think about making a markdown table, or using a monospaced section?

<img width="441" alt="image" src="https://user-images.githubusercontent.com/5635139/123495411-6f2ffc00-d5d8-11eb-9336-4c600c1815a4.png">

**Comment by EnricoMi** [comment]
The monospaced bit is discussed in #46. Tables turned out to be rendered with a very large margin, which I could not get look appealing. I am happy to discuss markdown proposals. You can hit the 'Edit' button on the comment created by the action and try to sketch out some better layout.

The particular problem in your example is that the `1`s have a different width than all other digits. This is not the case on other operating systems and browsers so numbers align there perfect to the pixel:

![grafik](https://user-images.githubusercontent.com/44700269/124487067-8fb53e80-ddae-11eb-8ff7-9c781ca1d9b2.png)

**Comment by max-sixty** [comment]
Thanks @EnricoMi . I had a go at a table layout, but on reflection it doesn't actually fit that well — it's not really a traditional rows & columns layout. The most promising I could think of is to reorient to pivot it to "Old" and "New" as columns, but even that doesn't capture the current first column.

#46 looks good!

It's surprising mine displays differently! I'm using firefox on Mac, and I get the same results with Chrome on Mac. I don't think I have any idiosyncratic settings.

I'll close this in the meantime. Thanks.

**Comment by EnricoMi** [comment]
@max-sixty thanks for giving this some thoughts, I find this one really tricky.
