### ISSUE TITLE
GitHub API error when creating check with more than 50 annotations

### ISSUE THREAD

**Issue by dgholz** [EnricoMi/publish-unit-test-result-action#212]
I was unaware of the `check_run_annotations` feature until I merged a PR that added this action, and I saw my job fail with this error:
```
2022-01-18 16:09:27 +0000 - publish-unit-test-results -  INFO - reading artifacts/**/*.xml
2022-01-18 16:09:29 +0000 - publish -  INFO - publishing success results for commit 3216c158b21d36f62d209672014e94160a428780
2022-01-18 16:09:31 +0000 - publish -  INFO - creating check
2022-01-18 16:09:33 +0000 - publish -  INFO - creating check
Traceback (most recent call last):
  File "/action/publish_unit_test_results.py", line 301, in <module>
    main(settings, gha)
  File "/action/publish_unit_test_results.py", line 102, in main
    Publisher(settings, gh, gha).publish(stats, results.case_results, conclusion)
  File "/action/publish/publisher.py", line 66, in publish
    check_run = self.publish_check(stats, cases, conclusion)
  File "/action/publish/publisher.py", line 242, in publish_check
    output=output)
  File "/usr/local/lib/python3.6/site-packages/github/Repository.py", line 3645, in create_check_run
    input=post_parameters,
  File "/usr/local/lib/python3.6/site-packages/github/Requester.py", line 355, in requestJsonAndCheck
    verb, url, parameters, headers, input, self.__customConnection(url)
  File "/usr/local/lib/python3.6/site-packages/github/Requester.py", line 378, in __check
    raise self.__createException(status, responseHeaders, output)
github.GithubException.GithubException: 422 {"message": "Validation Failed", "errors": [{"resource": "CheckRun", "code": "invalid", "field": "annotations"}], "documentation_url": "https://docs.github.com/rest/reference/checks#create-a-check-run"}
```

The repo I was working on has way more than 2000 tests, so I think it hit https://github.com/EnricoMi/publish-unit-test-result-action/blob/043296c976c53f4536194ebe3841ed720e04d496/python/publish/publisher.py#L238 more than once and tried to create a duplicate `check_run`, which the GitHub API didn't allow.

 I can see 50 annotations on the Unit Test Results check just fine, which has the first 2157 passing tests and 4 skipped tests listed.

**Comment by EnricoMi** [comment]
One thing that is strange is that your 2k tests need over 50 annotations. You must have very long test names to require that many annotations for those 2k tests. I have seen 16k tests that fit into 25 annotations: https://github.com/pydata/xarray/runs/4827976694. Can you give some input on that?

Adding more than 50 annotations is expected to be done by multiple requests creating the same check over and over again, which appends the annotations: https://github.com/stoplightio/spectral-action/issues/334#issue-703724929. Maybe this has changed since the time of implementation as I cannot find this bit in the current documentation any more.

I will test this 50 annotations limit (maybe it is gone), and test re-creating / updating a check.

Alternative is that the content of the annotation is bad.

Is the repo public? Can you point me to the workflow that fails?

Can you run the action with debug logging so I can see the content of the failing request?

```yaml
with:
  root_log_level: DEBUG
  log_level: DEBUG
```

Especially the `root_log_level` is important as it provides the content of the request.

**Comment by EnricoMi** [comment]
The limit of 50 annotations did not change, I found it:
https://docs.github.com/en/rest/reference/checks#create-a-check-run

It is hidden under `Properties of the output object`.

The problem might be that I am creating all these checks, not creating the check with the first 50 annotations and then updating it with more annotations. Will test and revise this.

**Comment by EnricoMi** [comment]
I have tested this in #215. It creates multiple checks while overwriting earlier ones. Only the last check remains. This is definitively wrong behaviour, but I cannot reproduce your error. Looks like yours is triggered by invalid annotation payload. I'd love to see that content.

**Comment by EnricoMi** [comment]
I have fixed the check creation for more than 50 annotations. Please give it a try by using this action temporarily:

```
uses: EnricoMi/publish-unit-test-result-action/composite@master
```

If the error persists, it is due to malformed annotation content (as the error suggests), not due to the action creating the check incorrectly (tested to work in https://github.com/EnricoMi/publish-unit-test-result-action/runs/4860016192).

**Comment by dgholz** [comment]
> You must have very long test names to require that many annotations for those 2k tests

You got it, our test names are extremely long. It's a private repo so I can't share the list with you…

I'll try with debug logging, and also try out the updated action.

**Comment by EnricoMi** [comment]
Please re-open once you have some payload that breaks as reported. I am very keen to get that fixed. Thanks!

**Comment by EnricoMi** [comment]
A fix has been released for the `Validation Failed`. Thanks for reporting!
