### ISSUE TITLE
Unexpected input junit_files

### ISSUE THREAD

**Issue by hailstorm75** [EnricoMi/publish-unit-test-result-action#290]
I'm attempting to upload my test results to the GitHub actions summary page.
I'm using ubuntu machines, and, as of writing this issue, the latest version of this action - v1.36

The `junit_files` parameter is, for some reason, not recognized.
Using the now deprecated `files` attribute also does not work.
Additionally, I get a **Could not find any files for \*.xml** error when attempting to use either parameter.

- [YAML](https://github.com/hailstorm75/MarkDoc.Core/blob/6edeece5775b1ea5ba7c26d3a3847354e302ad82/.github/workflows/dot-core.yml)
- [Job](https://github.com/hailstorm75/MarkDoc.Core/actions/runs/2399206202)

![image](https://user-images.githubusercontent.com/16069996/170800094-728dc75c-3160-4bad-9b18-a19414583963.png)

**Comment by hailstorm75** [comment]
From what I've gathered, the path cannot contain the `~` character. I've changed it from `~/TestResults/*.xml` to `artifacts/*.xml`. Additionally, I've fallen back to the `files` parameter.

Thus, this issue targets the fact that the `junit_files` is undocumented; thus, the warning is a false positive.
The expected behavior is for the parameter check to not throw a warning for said parameter, as it is valid, and instead throw a warning for the now deprecated `files` parameter.

Also, I suggest the issue with the paths is somehow addressed, as I'm using valid paths for the chosen operating system. Even substituting the `~` with `/home/runner/` results with the action not finding any test output files. Whether that is to be addressed or not is up to the dev team. If yes, I can create a new issue for it.

**Comment by EnricoMi** [comment]
The `junit_files` parameter only exist in master, that has not been released. I have removed it from master so that it is not misguiding users.

The documentation points to [glob](https://docs.python.org/3/library/glob.html), which implements the pattern expansion. There it says "No tilde expansion is done." So I would `~` not expect to work.

Absolute paths have shown not to work nicely with GitHub actions. I recommend to use relative paths.

In your case, instead of `mkdir ~/artifacts` try `mkdir artifacts`.

**Comment by hailstorm75** [comment]
Then I shall close the issue. Thank you!
