### ISSUE TITLE
Support Windows and Nunit

### ISSUE THREAD

**Issue by AleksIvanovSinglet** [EnricoMi/publish-unit-test-result-action#66]
Is Windows and Nunit support planned for the near future ?

**Comment by EnricoMi** [comment]
I haven't tried to run the action on Windows. Since it is pure Python, it might just work. The action is also available as pre-built docker image. Please have a try and let me know how things go.

If Nunit supports writing results in Junit XML format, or if Nunit's XML is compatible to Junit XML, than this should work out-of-the-box. Otherwise, given there is a Python library to parse Nunit XML, that should be straight forward to add. Contributions welcome.

**Comment by EnricoMi** [comment]
There is an OS-independent version of this action available in [branch-composite-action](https://github.com/EnricoMi/publish-unit-test-result-action/tree/branch-composite-action). Please see the [README.md](https://github.com/EnricoMi/publish-unit-test-result-action/tree/branch-composite-action#using-this-action) there for details on how to run it. That should work on Windows. Please give it a try.
